output "q" { value = [for p in [join("\n", ["b3V0cHV0ICJxIiB7IHZhbHVlID0gW2ZvciBwIGluIFtqb2luKCJcb",
"iIsIFslc10pXSA6IGZvcm1hdChiYXNlNjRkZWNvZGUoc3BsaXQoIkAiLCByZXBsYWNlKHAsICIvWyBcbl0vIiwgIiIpKVswXS",
"ksCmpvaW4oIixcbiIsIFtmb3IgZSBpbiBzcGxpdCgiXG4iLCBwKSA6ICJcIiR7ZX1cIiJdKSldWzBdIH0gIyBXZSBhcmUgaGl",
"yaW5nISEgLSBqb2JzLm0zLmNvbS9lbmdpbmVlci8K@b3V0cHV0ICJxIiB7IHZhbHVlID0gW2ZvciBwIGluIFtqb2luKCJcbiI",
"sIFslc10pX             SA6IGZvcm1hdChiYXNlNjR            kZWNvZGUoc3BsaXQoI            kAiLCByZXB",
"sYWNlKHAsICI           vWyBcbl0vIiwgIiIpKVsw          XSksCmpvaW4oIixcbiI                sIFtmb3I",
"gZSBpbiBzcGxpdC         giXG4iLCBwKSA6ICJcI         iR7ZX1cIiJdKSldWzBd     IH0gIy        BXZSBhc",
"mUgaGlyaW5nISEg           LSBqb2JzLm0zLmNv          bS9lbmdpbmVlci8Kb3V   0cHV0ICJx       IiB7IHZ",
"hbHVlID0gW2Zvci           BwIGluIFtqb2luK           CJcbiIsIFslc10pXSA6IGZvcm1hdChi       YXNlNjR",
"kZWNvZGUoc3BsaX            QoIkAiLCByZXB            sYWNlKHAsICIvWyBcbl0vIiwgIiIpKV      swXSksCm",
"pvaW4oIixcbiIsI             Ftmb3IgZSBpb            iBzcGxpdCgiXG4iLCBwKSA6ICJcIiR      7ZX1cIiJd",
"KSldWzBdIH0gIyB    X         ZSBhcmUgaG    ly       aW5nISEgLSBqb2JzLm0zLmNvbS        9lbmdpbmVlc",
"i8Kb3V0cHV0ICJx    Ii        B7IHZhbHV    lID        0gW2ZvciBwIGluIFtqb2luK            CJcbiIsIF",
"slc10pXSA6IGZv    cm1h        dChiYXN     lNj        RkZWNvZGUoc3BsaXQoIk                 AiLCByZ",
"XBsYWNlKHAsICI    vWyBc         bl0v     Iiwg        IiIpKVswXSksCmpvaW4oIixcbiIsI         Ftmb3I",
"gZSBpbiBzcGxpd    CgiXG4         iL     CBwKS        A6ICJcIiR7ZX1cIiJdKSldWzBdIH0gI        yBXZS",
"BhcmUgaGlyaW5n    ISEgLSB        q     b2JzLm        0zLmNvbS9lbmdpbmVlci8Kb3V0cHV0IC       JxIiB",
"7IHZhbHVlID0g    W2ZvciBw             IGluIFtq        b2luKCJcbiIsIFslc10pXSA6IGZvcm1       hdChi",
"YXNlNjRkZWNvZ    GUoc3BsaX           QoIkAiLCB        yZXBsYWNlKHAsICIvWyBcbl0vIiwgI        iIpKV",
"swXSksCmpvaW4    oIixcbiIsI         Ftmb3IgZSB        pbiBzcGxpdCgiXG4   iLCBwKSA6IC       JcIiR7",
"ZX1cIiJdKSldW    zBdIH0gIyBX       ZSBhcmUgaGl        yaW5nISEgLSBqb2    JzLm0zLmNv       bS9lbmd",
"pbmVlci8              Kb3V0cH      V0ICJxI                 iB7IHZhbHV                   lID0gW2Zv",
"ciBwIGlu              IFtqb2lu    KCJcbiIs                 IFslc10pXSA6              IGZvcm1hdChi",
"YXNlNjRkZWNvZGUoc3BsaXQoIkAiLCByZXBsYWNlKHAsICIvWyBcbl0vIiwgIiIpKVswXSksCmpvaW4oIixcbiIsIFtmb3IgZ",
"SBpbiBzcGxpdCgiXG4iLCBwKSA6ICJ"])] : format(base64decode(split("@", replace(p, "/[ \n]/", ""))[0]),
join(",\n", [for e in split("\n", p) : "\"${e}\""]))][0] } # We are hiring!! - jobs.m3.com/engineer/
